language: cpp
sudo: false

services:
  - docker

env:
  global:
    - NODE_VERSION="6.1.0"
    - RUBY_VERSION="2.3.1"
  matrix:
    - TARGET_ARCH=x64
    - TARGET_ARCH=x86

matrix:
  exclude:
    - os: osx
      env: TARGET_ARCH=x86

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      rm -rf ~/.nvm;
      git clone https://github.com/creationix/nvm.git ~/.nvm;
      source ~/.nvm/nvm.sh;
      nvm --version;
      nvm install $NODE_VERSION;
      node --version;
      npm --version;
      npm config set spin=false;
      rvm install $RUBY_VERSION;
      rvm use $RUBY_VERSION;
    fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      pip install codespell;
      gem install scss_lint;
      npm install -g bower;
      brew install afsctool;
      brew install jq;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      make info;
      make electron-develop;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ./scripts/build/docker/run-command.sh -r ${TARGET_ARCH} -s ${PWD} -c "make info && make electron-develop";
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      npm test;
      ./scripts/ci/ensure-staged-sass.sh;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ./scripts/build/docker/run-command.sh -r ${TARGET_ARCH} -s ${PWD} -c "xvfb-run --server-args=$XVFB_ARGS npm test && ./scripts/ci/ensure-staged-sass.sh";
    fi
